services:
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app/api
      - ./data:/app/data
      - ./models:/app/models
    environment:
      - ENV=development
    networks:
      - predictionnetwork
  good-website:
    build:
      context: ./website
      dockerfile: ./good/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./website/good:/app
      - ./website/shared:/app/shared
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - predictionnetwork

networks:
  predictionnetwork:
    driver: bridge